sample_dbt_project:
  outputs:
    dev:
      dataset: sampledbt
      fixed_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: poc-dna-automation-693335
      threads: 1
      timeout_seconds: 5
      type: bigquery
  target: dev